server:
  port: 8090

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/wms02?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 285369
spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=wms02;encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 285369

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??????
#    log-enable: true
